name: laravel-create-project

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Version
        run: docker-compose --version

      - name: Build Docker
        run: docker-compose up -d --build

      - name: PHP Version
        run: docker-compose exec -T web php --version

      - name: Composer Version
        run: docker-compose exec -T web composer --version

      - name: Create Laravel Project
        run: docker-compose exec -T web composer create-project --prefer-dist laravel/laravel .

      - name: Laravel Version
        run: docker-compose exec -T web php artisan --version

      - name: Laravel Migrate Testing
        run: docker-compose exec -T web php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T web php artisan migrate:refresh --seed

      - name: Laravel Seeding Testing
        run: docker-compose exec -T web php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker-compose exec -T web php artisan test
